services:
  postgres:
    image: postgres:17.3
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d currency_db" ]
      interval: 1s
      timeout: 1s
      retries: 5