service:
  server_port: "8090"

api:
  base_url: "https://latest.currency-api.pages.dev/v1/currencies"
  timeout_seconds: 10

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "admin"
  name: "currency_db"
  ssl_mode: "disable"
  migrations_path: "./currency/internal/migrations"

worker:
  schedule: "@daily"
  currency_pair:
    base_currency: "RUB"
    target_currency: "USD"